name: CI Server

on:
  push:
    branches:
      - server
  pull_request:
    branches:
      - server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: server

      - name: Build project
        run: npm run build
        working-directory: server

      - name: Run tests
        run: npm test
        working-directory: server
